# Generated by Django 3.0 on 2019-12-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='idn',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='bike',
            name='poi_x',
            field=models.CharField(default='0.0', max_length=5),
        ),
        migrations.AlterField(
            model_name='bike',
            name='poi_y',
            field=models.CharField(default='0.0', max_length=5),
        ),
    ]
